POST http://localhost:8080/client HTTP/1.1
Content-Type: application/json

{
  "name": "John Doee",
  "email": "go@go.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "7dc97a2b-aaa6-4565-8e09-2775db8c5f1f"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "55ff8900-8d56-4cef-b5f5-6c3e380faa1a",
    "account_id_to": "97794a9b-7eaf-4cca-8465-e90dcc33295f",
    "amount": 50
}
